// export const countries = [
//   { code: "IN", label: "+91" },
//   { code: "US", label: "+1" },
//   { code: "GB", label: "+44" },
//   { code: "AU", label: "+61" },
//   { code: "RU", label: "+7" },
// ];

export const countries = [
  { code: "AF", label: "+93" },
  { code: "AL", label: "+355" },
  { code: "DZ", label: "+213" },
  { code: "AS", label: "+1-684" },
  { code: "AD", label: "+376" },
  { code: "AO", label: "+244" },
  { code: "AI", label: "+1-264" },
  { code: "AG", label: "+1-268" },
  { code: "AR", label: "+54" },
  { code: "AM", label: "+374" },
  { code: "AW", label: "+297" },
  { code: "AU", label: "+61" },
  { code: "AT", label: "+43" },
  { code: "AZ", label: "+994" },

  { code: "BH", label: "+973" },
  { code: "BD", label: "+880" },
  { code: "BB", label: "+1-246" },
  { code: "BY", label: "+375" },
  { code: "BE", label: "+32" },
  { code: "BZ", label: "+501" },
  { code: "BJ", label: "+229" },
  { code: "BM", label: "+1-441" },
  { code: "BT", label: "+975" },
  { code: "BO", label: "+591" },
  { code: "BA", label: "+387" },
  { code: "BW", label: "+267" },
  { code: "BR", label: "+55" },
  { code: "BN", label: "+673" },
  { code: "BG", label: "+359" },

  { code: "KH", label: "+855" },
  { code: "CM", label: "+237" },
  { code: "CA", label: "+1" },
  { code: "CV", label: "+238" },
  { code: "CF", label: "+236" },
  { code: "TD", label: "+235" },
  { code: "CL", label: "+56" },
  { code: "CN", label: "+86" },
  { code: "CO", label: "+57" },
  { code: "KM", label: "+269" },
  { code: "CG", label: "+242" },
  { code: "CR", label: "+506" },
  { code: "HR", label: "+385" },
  { code: "CU", label: "+53" },
  { code: "CY", label: "+357" },
  { code: "CZ", label: "+420" },

  { code: "DK", label: "+45" },
  { code: "DJ", label: "+253" },
  { code: "DO", label: "+1-809" },

  { code: "EC", label: "+593" },
  { code: "EG", label: "+20" },
  { code: "SV", label: "+503" },
  { code: "EE", label: "+372" },
  { code: "ET", label: "+251" },

  { code: "FI", label: "+358" },
  { code: "FR", label: "+33" },

  { code: "GE", label: "+995" },
  { code: "DE", label: "+49" },
  { code: "GH", label: "+233" },
  { code: "GR", label: "+30" },
  { code: "GT", label: "+502" },

  { code: "HK", label: "+852" },
  { code: "HU", label: "+36" },

  { code: "IS", label: "+354" },
  { code: "IN", label: "+91" },
  { code: "ID", label: "+62" },
  { code: "IR", label: "+98" },
  { code: "IQ", label: "+964" },
  { code: "IE", label: "+353" },
  { code: "IL", label: "+972" },
  { code: "IT", label: "+39" },

  { code: "JP", label: "+81" },
  { code: "JO", label: "+962" },

  { code: "KE", label: "+254" },
  { code: "KW", label: "+965" },
  { code: "KZ", label: "+7" },
  { code: "KR", label: "+82" },

  { code: "LA", label: "+856" },
  { code: "LV", label: "+371" },
  { code: "LB", label: "+961" },
  { code: "LT", label: "+370" },
  { code: "LU", label: "+352" },

  { code: "MY", label: "+60" },
  { code: "MV", label: "+960" },
  { code: "MX", label: "+52" },
  { code: "MA", label: "+212" },

  { code: "NP", label: "+977" },
  { code: "NL", label: "+31" },
  { code: "NZ", label: "+64" },
  { code: "NG", label: "+234" },
  { code: "NO", label: "+47" },

  { code: "OM", label: "+968" },

  { code: "PK", label: "+92" },
  { code: "PH", label: "+63" },
  { code: "PL", label: "+48" },
  { code: "PT", label: "+351" },

  { code: "QA", label: "+974" },

  { code: "RO", label: "+40" },
  { code: "RU", label: "+7" },

  { code: "SA", label: "+966" },
  { code: "SG", label: "+65" },
  { code: "ZA", label: "+27" },
  { code: "ES", label: "+34" },
  { code: "SE", label: "+46" },
  { code: "CH", label: "+41" },

  { code: "TH", label: "+66" },
  { code: "TR", label: "+90" },

  { code: "UA", label: "+380" },
  { code: "AE", label: "+971" },
  { code: "GB", label: "+44" },
  { code: "US", label: "+1" },

  { code: "VN", label: "+84" },
  { code: "ZW", label: "+263" },
];

